language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - phpunit --verbose --coverage-clover build/logs/clover.xml
    - phpenv config-rm xdebug.ini || return 0

after_script:
  - CODECLIMATE_REPO_TOKEN="f34da85cf2395de68d6b4aeacd0274a225faeba0afbe91f034fb9c830ec71152" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token: f34da85cf2395de68d6b4aeacd0274a225faeba0afbe91f034fb9c830ec71152

after_success:
    - php vendor/bin/coveralls -v
